name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Run CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Cache Cypress Binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress
        run: pnpm exec cypress install

      - name: Set up DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Prisma Migrations (Development)
        run: pnpm prisma migrate dev --name init

      - name: Run ESLint (Linting)
        run: pnpm run lint

      - name: Run TypeScript Check
        run: pnpm run type-check

      - name: Run Unit Tests
        run: pnpm run test -- --ci --coverage

      - name: Start Next.js Server
        run: pnpm run dev &

      - name: Wait for Next.js to be Ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Cypress Tests
        run: pnpm run test:e2e

  deploy:
    name: Deploy to Vercel
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Set up DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Prisma Migrations (Production)
        run: pnpm prisma migrate deploy

      - name: Build Next.js project
        run: pnpm run build

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
