name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Run CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Versão mais recente do pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set up DATABASE_URL
        run: echo "DATABASE_URL=file:./dev.db" >> $GITHUB_ENV

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Prisma Migrations
        run: pnpm prisma migrate dev --name init

      - name: Run ESLint (Linting)
        run: pnpm run lint

      - name: Run TypeScript Check
        run: pnpm run type-check

      - name: Run Unit Tests
        run: pnpm run test -- --ci --coverage

      - name: Start Next.js Server
        run: pnpm run dev & # Roda o servidor Next.js em background

      - name: Wait for Next.js to be Ready
        run: npx wait-on http://localhost:3000 # Aguarda o servidor iniciar

      - name: Run Cypress Tests
        run: pnpm run test:e2e


  deploy:
    name: Deploy to Vercel
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js project
        run: pnpm run build

      - name: Deploy to Vercel
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_<YOUR_PROJECT_ID>" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
