name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  ci:
    name: Run CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.12.0  # 🔥 Mesma versão que sua máquina

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0  # 🔥 Mesma versão que sua máquina
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Debug DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"

      - name: Set up DATABASE_URL
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          export DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Prisma Migrations (Development)
        run: pnpm prisma db push

      - name: Run ESLint (Linting)
        run: pnpm run lint

      - name: Run TypeScript Check
        run: pnpm run type-check

      - name: Run Unit Tests
        run: pnpm run test -- --ci --coverage

  deploy:
    name: Deploy to Vercel
    needs: ci
    runs-on: ubuntu-latest
    environment: Production 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: "pnpm"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.TALKBOT_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.TALKBOT_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.TALKBOT_TOKEN }}
